export const data = [
    { month: 'Jan', city: 'Tokyo', temperature: 7 },
    { month: 'Jan', city: 'London', temperature: 3.9 },
    { month: 'Feb', city: 'Tokyo', temperature: 6.9 },
    { month: 'Feb', city: 'London', temperature: 4.2 },
    { month: 'Mar', city: 'Tokyo', temperature: 9.5 },
    { month: 'Mar', city: 'London', temperature: 5.7 },
    { month: 'Apr', city: 'Tokyo', temperature: 14.5 },
    { month: 'Apr', city: 'London', temperature: 8.5 },
    { month: 'May', city: 'Tokyo', temperature: 18.4 },
    { month: 'May', city: 'London', temperature: 11.9 },
    { month: 'Jun', city: 'Tokyo', temperature: 21.5 },
    { month: 'Jun', city: 'London', temperature: 15.2 },
    { month: 'Jul', city: 'Tokyo', temperature: 25.2 },
    { month: 'Jul', city: 'London', temperature: 17 },
    { month: 'Aug', city: 'Tokyo', temperature: 26.5 },
    { month: 'Aug', city: 'London', temperature: 16.6 },
    { month: 'Sep', city: 'Tokyo', temperature: 23.3 },
    { month: 'Sep', city: 'London', temperature: 14.2 },
    { month: 'Oct', city: 'Tokyo', temperature: 18.3 },
    { month: 'Oct', city: 'London', temperature: 10.3 },
    { month: 'Nov', city: 'Tokyo', temperature: 13.9 },
    { month: 'Nov', city: 'London', temperature: 6.6 },
    { month: 'Dec', city: 'Tokyo', temperature: 9.6 },
    { month: 'Dec', city: 'London', temperature: 4.8 },
  ];



export const phoneData = [
    { feature: 'Battery', value: 0.22, phone: 'iPhone' },
    { feature: 'Brand', value: 0.28, phone: 'iPhone' },
    { feature: 'Contract', value: 0.29, phone: 'iPhone' },
    { feature: 'Design', value: 0.17, phone: 'iPhone' },
    { feature: 'Internet', value: 0.22, phone: 'iPhone' },
    { feature: 'Large', value: 0.02, phone: 'iPhone' },
    { feature: 'Price', value: 0.21, phone: 'iPhone' },
    { feature: 'Smartphone', value: 0.5, phone: 'iPhone' },
    { feature: 'Battery', value: 0.27, phone: 'Samsung' },
    { feature: 'Brand', value: 0.16, phone: 'Samsung' },
    { feature: 'Contract', value: 0.35, phone: 'Samsung' },
    { feature: 'Design', value: 0.13, phone: 'Samsung' },
    { feature: 'Internet', value: 0.2, phone: 'Samsung' },
    { feature: 'Large', value: 0.13, phone: 'Samsung' },
    { feature: 'Price', value: 0.35, phone: 'Samsung' },
    { feature: 'Smartphone', value: 0.38, phone: 'Samsung' },
    { feature: 'Battery', value: 0.26, phone: 'Nokia Smartphone' },
    { feature: 'Brand', value: 0.1, phone: 'Nokia Smartphone' },
    { feature: 'Contract', value: 0.3, phone: 'Nokia Smartphone' },
    { feature: 'Design', value: 0.14, phone: 'Nokia Smartphone' },
    { feature: 'Internet', value: 0.22, phone: 'Nokia Smartphone' },
    { feature: 'Large', value: 0.04, phone: 'Nokia Smartphone' },
    { feature: 'Price', value: 0.41, phone: 'Nokia Smartphone' },
    { feature: 'Smartphone', value: 0.3, phone: 'Nokia Smartphone' },
  ];