import permissions from './permissions';
/* eslint-disable */
export const getSupplierMenu = (pid, storeId, prefix, basicPrefix) => ({
  monitorTrackId: '1375dab0-df43-431e-a849-e1b05970f1a3',
  globalTicket: '09d6eb5c21034864ba40ec63a80937d8',
  data: {
    menus: {
      '1': {
        child: {
          '41': {
            child: {
              '411': {
                child: {
                  '4111': {
                    child: null,
                    code: 'supplier#app.qualification.application',
                    icon: null,
                    id: 365366059,
                    isBlank: false,
                    isChecked: true,
                    isShow: true,
                    level: 4,
                    name: '我的资质',
                    parent: 365366048,
                    sortNum: 1,
                    url: `${prefix}${pid}/${storeId}/qualification/application`,
                  },
                },
                code: 'supplier#app.qualification.apply',
                icon: null,
                id: 365366057,
                isBlank: false,
                isChecked: true,
                isShow: true,
                level: 4,
                name: '入驻申请',
                parent: 365366048,
                sortNum: 1,
                url: `${prefix}${pid}/${storeId}/qualification/apply`,
              },
              '412': {
                child: null,
                code: 'supplier#app.qualification.mine',
                icon: null,
                id: 365366059,
                isBlank: false,
                isChecked: true,
                isShow: true,
                level: 4,
                name: '我的资质',
                parent: 365366048,
                sortNum: 1,
                url: `${prefix}${pid}/${storeId}/qualification/mine`,
              },
              // '413': {
              //     child: null,
              //     code: 'supplier#app.qualification.edit',
              //     icon: null,
              //     id: 365366088,
              //     isBlank: false,
              //     isChecked: true,
              //     isShow: true,
              //     level: 4,
              //     name: '编辑资质',
              //     parent: 365366048,
              //     sortNum: 1,
              //     url: `${prefix}${pid}/${storeId}/qualification/edit`,
              // },
            },
            code: 'supplier#app.qualification.apply',
            icon: '',
            id: 365366048,
            isBlank: false,
            isChecked: true,
            isShow: true,
            level: 3,
            name: '资质管理',
            parent: 365366047,
            sortNum: 1,
            url: '',
          },
        },
        code: 'supplier#app.qualification',
        icon: 'icon-dashboard',
        id: 365366047,
        isBlank: false,
        isChecked: true,
        isShow: true,
        level: 2,
        name: '资质',
        parent: 365366027,
        sortNum: 4,
        url: `${prefix}${pid}/${storeId}/qualification/apply`,
      },
      '2': {
        child: {
          '11': {
            child: {
              '111': {
                child: {
                  '1111': {
                    child: null,
                    code: 'supplier#app.goods.detail',
                    icon: '',
                    id: 365366030,
                    isBlank: false,
                    isChecked: true,
                    isShow: false,
                    level: 4,
                    name: '商品详情',
                    parent: 365366029,
                    sortNum: 1,
                    url: `${prefix}${pid}/${storeId}/goods/detail`,
                  },
                  '2': {
                    child: null,
                    code: 'supplier#app.goods.edit',
                    icon: '',
                    id: 365366031,
                    isBlank: false,
                    isChecked: true,
                    isShow: false,
                    level: 4,
                    name: '商品编辑',
                    parent: 365366029,
                    sortNum: 2,
                    url: `${prefix}${pid}/${storeId}/goods/edit`,
                  },
                  '3': {
                    child: null,
                    code: 'supplier#app.goods.import',
                    icon: '',
                    id: 365366032,
                    isBlank: false,
                    isChecked: true,
                    isShow: false,
                    level: 4,
                    name: '导入商品',
                    parent: 365366029,
                    sortNum: 3,
                    url: `${prefix}${pid}/${storeId}/goods/import`,
                  },
                },
                code: 'supplier#app.goods.list',
                icon: '',
                id: 365366029,
                isBlank: false,
                isChecked: true,
                isShow: true,
                level: 3,
                name: '商品列表',
                parent: 365366028,
                sortNum: 1,
                url: `${prefix}${pid}/${storeId}/goods/list`,
              },
              '112': {
                child: {
                  '1': {
                    child: null,
                    code: 'supplier#app.goods.distribution.create',
                    icon: '',
                    id: 365366034,
                    isBlank: false,
                    isChecked: true,
                    isShow: false,
                    level: 4,
                    name: '新建分销模板',
                    parent: 365366033,
                    sortNum: 1,
                    url: `${prefix}${pid}/${storeId}/distribution/create`,
                  },
                  '2': {
                    child: null,
                    code: 'supplier#app.goods.distribution.edit',
                    icon: '',
                    id: 365366035,
                    isBlank: false,
                    isChecked: true,
                    isShow: false,
                    level: 4,
                    name: '编辑分销模板',
                    parent: 365366033,
                    sortNum: 2,
                    url: `${prefix}${pid}/${storeId}/distribution/create`,
                  },
                },
                code: 'supplier#app.goods.distribution',
                icon: '',
                id: 365366033,
                isBlank: false,
                isChecked: true,
                isShow: true,
                level: 3,
                name: '分销模板',
                parent: 365366028,
                sortNum: 2,
                url: `${prefix}${pid}/${storeId}/distribution/list`,
              },
              '113': {
                child: {
                  '1': {
                    child: null,
                    code: 'supplier#app.freight.template.create',
                    icon: '',
                    id: 365366037,
                    isBlank: false,
                    isChecked: true,
                    isShow: false,
                    level: 4,
                    name: '新建运费模板',
                    parent: 365366036,
                    sortNum: 1,
                    url: `${prefix}${pid}/${storeId}/freight/template/add`,
                  },
                  '2': {
                    child: null,
                    code: 'supplier#app.freight.template.edit',
                    icon: '',
                    id: 365366038,
                    isBlank: false,
                    isChecked: true,
                    isShow: false,
                    level: 4,
                    name: '编辑运费模板',
                    parent: 365366036,
                    sortNum: 2,
                    url: `${prefix}${pid}/${storeId}/freight/template/edit`,
                  },
                },
                code: 'supplier#app.freight.template.list',
                icon: '',
                id: 365366036,
                isBlank: false,
                isChecked: true,
                isShow: true,
                level: 3,
                name: '运费模板',
                parent: 365366028,
                sortNum: 3,
                url: `${prefix}${pid}/${storeId}/freight/template/list`,
              },
            },
            code: 'supplier#app.goods',
            icon: '',
            id: 365366028,
            isBlank: false,
            isChecked: true,
            isShow: true,
            level: 2,
            name: '商品管理',
            parent: 365366027,
            sortNum: 1,
            url: '',
          },
        },
        code: 'supplier#app.goods',
        icon: 'icon-goods',
        id: 365366028,
        isBlank: false,
        isChecked: true,
        isShow: true,
        level: 2,
        name: '商品',
        parent: 365366027,
        sortNum: 1,
        url: `${prefix}${pid}/${storeId}/goods/list`,
      },
      '3': {
        child: {
          21: {
            child: {
              211: {
                code: 'supplier#app.stock.list',
                icon: '',
                id: 365366040,
                isBlank: false,
                isChecked: true,
                isShow: true,
                level: 3,
                name: '库存列表',
                parent: 365366039,
                sortNum: 1,
                url: `${prefix}${pid}/${storeId}/stock`,
              },
            },
            code: 'supplier#app.stock',
            icon: '',
            id: 365366039,
            isBlank: false,
            isChecked: true,
            isShow: true,
            level: 2,
            name: '库存管理',
            parent: 365366027,
            sortNum: 2,
            url: '',
          },
        },
        code: 'supplier#app.stock',
        icon: 'icon-kucun',
        id: 365366039,
        isBlank: false,
        isChecked: true,
        isShow: true,
        level: 2,
        name: '库存',
        parent: 365366027,
        sortNum: 2,
        url: `${prefix}${pid}/${storeId}/stock`,
      },
      '4': {
        child: {
          '31': {
            child: {
              '311': {
                child: {
                  '1': {
                    child: null,
                    code: 'supplier#app.order.deliver',
                    icon: '',
                    id: 365366043,
                    isBlank: false,
                    isChecked: true,
                    isShow: false,
                    level: 4,
                    name: '批量发货',
                    parent: 365366042,
                    sortNum: 1,
                    url: `${prefix}${pid}/${storeId}/order/deliver`,
                  },
                  '2': {
                    child: null,
                    code: 'supplier#app.order.detail',
                    icon: '',
                    id: 365366044,
                    isBlank: false,
                    isChecked: true,
                    isShow: false,
                    level: 4,
                    name: '订单详情',
                    parent: 365366042,
                    sortNum: 2,
                    url: `${prefix}${pid}/${storeId}/order/detail`,
                  },
                },
                code: 'supplier#app.order.list',
                icon: '',
                id: 365366042,
                isBlank: false,
                isChecked: true,
                isShow: true,
                level: 3,
                name: '订单列表',
                parent: 365366041,
                sortNum: 1,
                url: `${prefix}${pid}/${storeId}/order/list`,
              },
              '312': {
                child: {
                  '1': {
                    child: null,
                    code: 'supplier#app.permission.detail',
                    icon: '',
                    id: 365366046,
                    isBlank: false,
                    isChecked: true,
                    isShow: false,
                    level: 4,
                    name: '维权订单详情',
                    parent: 365366045,
                    sortNum: 1,
                    url: `${prefix}${pid}/${storeId}/permission/detail`,
                  },
                },
                code: 'supplier#app.permission',
                icon: '',
                id: 365366045,
                isBlank: false,
                isChecked: true,
                isShow: true,
                level: 3,
                name: '维权订单',
                parent: 365366041,
                sortNum: 2,
                url: `${prefix}${pid}/${storeId}/permission/list`,
              },
            },
            code: 'supplier#app.order',
            icon: '',
            id: 365366041,
            isBlank: false,
            isChecked: true,
            isShow: true,
            level: 2,
            name: '订单管理',
            parent: 365366027,
            sortNum: 3,
            url: '',
          },
        },
        code: 'supplier#app.order',
        icon: 'icon-business',
        id: 365366041,
        isBlank: false,
        isChecked: true,
        isShow: true,
        level: 2,
        name: '订单',
        parent: 365366027,
        sortNum: 3,
        url: `${prefix}${pid}/${storeId}/order/list`,
      },
      /*'5': {
                child: {
                    '1': {
                        child: {
                            '1': {
                                child: null,
                                code: 'foundation#app.finance.accountedit',
                                icon: '',
                                id: 365366052,
                                isBlank: false,
                                isChecked: true,
                                isShow: false,
                                level: 4,
                                name: '提现账户修改',
                                parent: 365366051,
                                sortNum: 1,
                                url:
                                    'http://basis.console.dev.weimob.com/#/app/1254/1470154/finance/accountedit',
                            },
                        },
                        code: 'foundation#app.finance.account',
                        icon: '',
                        id: 365366051,
                        isBlank: false,
                        isChecked: true,
                        isShow: true,
                        level: 3,
                        name: '我的账户',
                        parent: 365366050,
                        sortNum: 1,
                        url:
                            'http://basis.console.dev.weimob.com/#/app/1254/1470154/finance/account',
                    },
                    '2': {
                        child: null,
                        code: 'foundation#app.finance.dealport',
                        icon: '',
                        id: 365366053,
                        isBlank: false,
                        isChecked: true,
                        isShow: true,
                        level: 3,
                        name: '交易订单',
                        parent: 365366050,
                        sortNum: 2,
                        url:
                            'http://basis.console.dev.weimob.com/#/app/1254/1470154/finance/dealport',
                    },
                    '3': {
                        child: null,
                        code: 'foundation#app.finance.refund',
                        icon: '',
                        id: 365366054,
                        isBlank: false,
                        isChecked: true,
                        isShow: true,
                        level: 3,
                        name: '退款订单',
                        parent: 365366050,
                        sortNum: 3,
                        url:
                            'http://basis.console.dev.weimob.com/#/app/1254/1470154/finance/refund',
                    },
                    '4': {
                        child: null,
                        code: 'foundation#app.finance.withdrawport',
                        icon: '',
                        id: 365366055,
                        isBlank: false,
                        isChecked: true,
                        isShow: true,
                        level: 3,
                        name: '提现订单',
                        parent: 365366050,
                        sortNum: 4,
                        url:
                            'http://basis.console.dev.weimob.com/#/app/1254/1470154/finance/withdrawport',
                    },
                },
                code: 'foundation#app.finance',
                icon: 'icon-finacial',
                id: 365366050,
                isBlank: false,
                isChecked: true,
                isShow: true,
                level: 2,
                name: '财务',
                parent: 365366027,
                sortNum: 5,
                url: `${basicPrefix}${pid}/${storeId}/finance/account`,
            },*/
      '6': {
        child: {
          '1': {
            code: 'supplier#app.finance',
            icon: 'icon-finacial',
            id: 365366050,
            isBlank: false,
            isChecked: true,
            isShow: true,
            level: 2,
            name: '财务',
            parent: 365366027,
            sortNum: 5,
            url: '',
            child: {
              '1': {
                child: {
                  '1': {
                    child: null,
                    code: 'supplier#app.finance.accountedit',
                    icon: '',
                    id: 365366052,
                    isBlank: false,
                    isChecked: true,
                    isShow: false,
                    level: 4,
                    name: '提现账户修改',
                    parent: 365366051,
                    sortNum: 1,
                    url: `${prefix}${pid}/${storeId}/finance/accountedit`,
                  },
                },
                code: 'supplier#app.finance.account',
                icon: '',
                id: 365366051,
                isBlank: false,
                isChecked: true,
                isShow: true,
                level: 3,
                name: '我的账户',
                parent: 365366050,
                sortNum: 1,
                url: `${prefix}${pid}/${storeId}/finance/account`,
              },
              '2': {
                child: null,
                code: 'supplier#app.finance.dealport',
                icon: '',
                id: 365366053,
                isBlank: false,
                isChecked: true,
                isShow: true,
                level: 3,
                name: '交易订单',
                parent: 365366050,
                sortNum: 2,
                url: `${prefix}${pid}/${storeId}/finance/dealport`,
              },
              '3': {
                child: null,
                code: 'supplier#app.finance.refund',
                icon: '',
                id: 365366054,
                isBlank: false,
                isChecked: true,
                isShow: true,
                level: 3,
                name: '退款订单',
                parent: 365366050,
                sortNum: 3,
                url: `${prefix}${pid}/${storeId}/finance/refund`,
              },
              '4': {
                child: null,
                code: 'supplier#app.finance.withdrawport',
                icon: '',
                id: 365366055,
                isBlank: false,
                isChecked: true,
                isShow: true,
                level: 3,
                name: '提现订单',
                parent: 365366050,
                sortNum: 4,
                url: `${prefix}${pid}/${storeId}/finance/withdrawport`,
              },
            },
          },
        },
        code: 'supplier#app.finance',
        icon: 'icon-finacial',
        id: 365366050,
        isBlank: false,
        isChecked: true,
        isShow: true,
        level: 2,
        name: '财务',
        parent: 365366027,
        sortNum: 5,
        url: `${prefix}${pid}/${storeId}/finance/account`,
      },
    },
    keys: permissions,
    //keys:
    // 'ecApp#work.statistics#all;ec#app.marketing.discountCode;ec#app.marketing.discountStatistics;ec#app.marketing.edit;ec#app.marketing.detail;ec#app.marketing.couponCodeCreate;ec#app.marketing.couponCodeList;ec#app.marketing.list;promotion#app.bargain.participant;promotion#app.bargain.wares;promotion#app.bargain.activityEdit;promotion#app.bargain.activity;ec#app.marketing.create;promotion#app.bargain.statistics;promotion#app.bargain.waresEdit;ec#app.marketing.fullDiscountCreateEnd;ec#app.marketing.fullDiscountList;ec#app.marketing.fullDiscountEdit;ec#app.customer.marketing.consumption;ec#app.customer.marketing.activatecard;ec#app.customer.marketing.addactivatecard;ec#app.marketing.discountedit;ec#app.marketing.couponCodeEdit;ec#app.marketing.couponCodeRepertory;ec#app.marketing.discountlist;ec#app.marketing.discountaddgoods;ec#app.marketing.discountmanage;promotion#app.pintuan.activityEdit;promotion#app.pintuan.activity;promotion#app.pintuan.wares;promotion#app.pintuan.participant;foundation#app.marketing.center;promotion#app.pintuan.waresEdit;ec#app.functionaldetails;ec#app.marketing.iframes;ec#app.customer.marketing.addconsumption;ec#app.customer.marketing.addrecharge;ec#app.customer.marketing.recharge;ec#app.customer.marketing.upgrade;ec#app.customer.marketing.addupgrade;activity#app.egg.list;activity#app.egg.prize;activity#app.egg.player;activity#app.egg.charts;activity#app.egg.edit;activity#app.egg.record;activity#app.box.list;activity#app.box.prize;promotion#app.recommend.activityEdit;ec#app.marketing.marketPromotionList;promotion#app.recommend.joinList;ec#app.marketing.privilegeaddgoods;activity#app.scratch.list;activity#app.scratch.player;activity#app.scratch.charts;activity#app.scratch.edit;ec#app.order.orderlist.deliverlist;ec#app.order.orderlist.batchdistribute;ec#app.order.orderlist.cycleList;ec#app.order.orderlist.orderdetail;ec#app.order.orderlist.list;wisdom#app.goods.single.category;wisdom#app.goods.single.import;wisdom#app.goods.single.add;wisdom#app.goods.single.list;ec#app.goods.management.goodsComment;wisdom#app.goods.management.goodsDetail;wisdom#app.goods.management.goodslist;ecApp#work.goods#all;ec#app.customer.marketing.integral;ec#app.customer.marketing.balanceset;ec#app.customer.manage.editCard;ec#app.customer.manage.createCard;ec#app.customer.manage.membercard;ec#app.member.cusDetail;ec#app.member.preOpenCard;ec#app.order.orderlist.distributelist;ec#app.order.orderlist.mention;ec#app.order.orderlist.refunddetail;ec#app.order.orderlist.batchimport;ec#app.order.orderlist.batchdeliver;ec#app.order.orderlist.refundlist;foundation#app.wechat.miniApp.list;wechat#app.wechat.miniApp.returnCallback;foundation#app.wechat.miniApp.returnCallback;ec#app.wechat.miniApp.curretVersionlist;foundation#app.custommenu.edit;foundation#app.custommenu.list;foundation#app.wechat.officalAccountManagement.officalAccountSet;foundation#app.autoreply.follow;foundation#app.autoreply.followEdit;foundation#app.autoreply.keyword;foundation#app.autoreply.keywordEdit;foundation#app.autoreply.msg;foundation#app.autoreply.msgEdit;foundation#app.autoreply.msgSyn;ec#app.customer.manage.customerlabelEdit;ec#app.customer.manage.customerlabelMag;ec#app.customer.manage.customerlist;ec#app.customer.manage.customerlabel;ec#app.customer.manage.cusdetail;foundation#app.material.poi;foundation#app.material.poiEdit;foundation#app.material.video;foundation#app.material.videoEdit;foundation#app.material.audio;foundation#app.material.audioEdit;foundation#app.material.tuwenEdit;foundation#app.material.img;foundation#app.material.imgAdd;retail#app.setting.shopset.switch;ecApp#work.invitecustomer#all;foundation#app.qualification.application.progress;foundation#app.wechat.officalAccountManagement.officalAccountSet;ec#app.store.design.step_2.config;ec#app.dashboard;ec#app.store.design.list;ec#app.store.design.step_1;ec#app.store.design.step_2;ec#app.store.design.navList;ec#app.store.design.editNav;ec#app.store.design.addNav;ec#app.store.design.style;ec#app.store.design.categoryTpl;ec#app.store.design.listTpl;ec#app.goods.management.addGoods;ec#app.goods.management.goodslist;ec#app.goods.management.goodsTag;ec#app.goods.management.goodsGroup;ec#app.goods.management.goodsDetailsList;ec#app.goods.management.goodsDetailsStep1;ec#app.goods.management.goodsDetailsStep2.config;ec#app.goods.management.goodsDetailsStep2;wisdom#app.goods.manage.edit;wisdom#app.goods.manage.list;wisdom#app.goods.manage.label;wisdom#app.goods.manage.group;ec#app.goods.management.goodsImport;wisdom#app.goods.manage.template;ecApp#work.reservations#all;wisdom#app.shopguide.guidemanage.profit;wisdom#app.shopguide.guidemanage.voucherSet;wisdom#app.shopguide.guidemanage.guideSet;wisdom#app.shopguide.guidemanage.importGuide;wisdom#app.shopguide.guidemanage.import;wisdom#app.shopguide.guidemanage.guideManageList;wisdom#app.shopguide.guidemanage.addGuide;wisdom#app.doorBackstage.storeLabel;ec#app.door.limit;ec#app.door.roled;ec#app.door.commodity;ec#app.door.doordeliverset1;ec#app.door.doormention;ec#app.door.doorcitylimit;ec#app.door.dooraddfreight;ec#app.door.decorate;ec#app.door.doorSetup;ec#app.door.doornewtion;ec#app.door.list;wisdom#app.stock.presentation.purchase;wisdom#app.stock.presentation.shipment;wisdom#app.stock.stockSearch;wisdom#app.stock.inventory.supplierDetail;wisdom#app.stock.inventory.stockChecks;wisdom#app.stock.inventory.stockChecksDetail;wisdom#app.stock.inventory.stockControl;wisdom#app.stock.inventory.supplier;wisdom#app.stock.inventory.placingEntry;wisdom#app.stock.inventory.placingEntryDetail;wisdom#app.stock.inventory.storeStock;wisdom#app.stock.import.store;wisdom#app.stock.inventory.stockDetail;wisdom#app.stock.inventory.godownEntry;wisdom#app.stock.inventory.godownEntryDetail;mkt#app.generalize.adsuccess.body.schedule;mkt#app.generalize.adsuccess.body.orientation;mkt#app.generalize.addPlan;mkt#app.generalize.plangroup;mkt#app.generalize.adsuccess.body;mkt#app.generalize.publicAccount.add;mkt#app.generalize.adDetail.body;mkt#app.generalize.editCreativeWxFriend;mkt#app.generalize.adDetail.body.orientation;mkt#app.generalize.adDetail.body.schedule;mkt#app.generalize.editCreativeIsTsa;mkt#app.generalize.addCreativeIsTsa;mkt#app.generalize.adsuccess;mkt#app.generalize.addCreativeWxFriend;mkt#app.generalize.addGeneralize;mkt#app.generalize.adgroup;mkt#app.generalize.adDetail;mkt#app.generalize.editGeneralize;mkt#app.generalize.survey;ecApp#work.order#all;ec#app.datamigration.shoptodata;ecApp#work.rights#all;mkt#app.generalize.introduce;mkt#app.generalize.publicAccount.info;mkt#app.generalize.publicAccount;mkt#app.generalize.financialDetails;mkt#app.generalize.transfer;foundation#app.h5pay.list;foundation#app.pay.home.payment;ec#app.setting.shopset.payset;ec#app.datamigration.goodsimport;ec#app.setting.shopset.offline;foundation#app.company.list;ec#app.setting.systemset.messagenotificate;ec#app.setting.shopset.generalset;ec#app.setting.systemset.loglist;ec#app.setting.systemset.roled;ec#app.setting.systemset.staffed;ec#app.setting.systemset.accountmanagement;foundation#app.multistore.detail;foundation#app.multistore.register;foundation#app.multistore.manage;foundation#app.multistore.config;foundation#app.paymentAccount.bindChannel;foundation#app.paymentAccount.apply;foundation#app.paymentAccount.list;foundation#app.fullScene.home;foundation#app.fullScene.config;foundation#app.fullScene.offline;foundation#app.manage.home;foundation#app.manage.configuration;foundation#app.manage.config;foundation#app.manage.account;foundation#app.manage.list;foundation#app.multistore.list;foundation#app.qualification.application.addQualification;foundation#app.qualification.application.information;foundation#app.qualification.application.advertisement;foundation#app.qualification.application.adAddQualification;foundation#app.qualification.application.status;foundation#app.payment.home;foundation#app.fullScene.list;ec#app.setting.shopset.addcustomitem;ec#app.setting.shopset.addressliblist;ec#app.setting.shopset.batchmention;ec#app.setting.shopset.logisticsSetting;ec#app.setting.shopset.addmention;ec#app.setting.shopset.mention;foundation#app.qualification.application.sign;foundation#app.qualification.application.progress;ec#app.setting.shopset.editcompany;ec#app.setting.shopset.deliverset1;foundation#app.logistics.logisticsSetting;foundation#app.logistics.logisticsRecharge;ec#app.setting.shopset.addfreight;foundation#app.logistics.rechargeCenter;ecApp#work#all;ec#app.setting.shopset.citylimit;ecApp#;ec#app.setting.shopset.addaddresslib;ec#app.financial.financialManage.weimobDetail;ec#app.financial.financialManage.marketing;foundation#app.withdraw;tweeter#app.sdp.recommend.award;ec#app.financial.financialManage.balancelist;ec#app.financial.financialManage.integraldetail;ec#app.setting.shopset.shopinfo;foundation#app.logistics.logisticsFee;ec#app.financial.financialManage.cashDetail;ec#app.financial.financialManage.balanceAccountDetail;ec#app.financial.financialManage.balanceAccount;ec#app.datacube.market.summary;ec#app.datacube.market.daogou;ec#app.datacube.trade.search;ec#app.datacube.trade.store;ec#app.datacube.trade.goods;ec#app.datacube.group.loyalty;ec#app.datacube.service.verificate;ec#app.datacube.service.customerConversion;ec#app.datacube.store.profile;ec#app.datacube.market.sdpSummary;ec#app.datacube.warehouse.fetch;ec#app.datacube.warehouse.downloadcenter;ec#app.datacube.flow.remain;ec#app.datacube.flow.direction;ec#app.datacube.group.nature;ec#app.datacube.warehouse.report.modify;ec#app.datacube.warehouse.report;ec#app.datacube.flow.detection;ec#app.marketing.reservation;ec#app.marketing.reservationDetail;ec#app.marketing.reservationsmanage;ec#app.marketing.sheetDetail;ec#app.marketing.multiOnePriceEdit;ec#app.marketing.freeExpressList;ec#app.marketing.freeExpressCreateEnd;ec#app.marketing.freeExpressEdit;ec#app.marketing.orderIframes;ec#app.marketing.appIframes;ec#app.marketing.calendar;ec#app.marketing.searchSource;foundation#app.upgrade.list;foundation#app.upgrade.edit;zhan#app.workspace;zhan#app.zhan.goToCreatZhan;zhan#app.flow.analytics.visitors;zhan#app.flow.analytics.pages;tweeter#app.sdp.sdpSetting.basis;tweeter#app.sdp.goods.list;tweeter#app.sdp.goods.sdpList;zhan#app.treasure.list;tweeter#app.sdp.recommend.detail;tweeter#app.sdp.material.list;tweeter#app.sdp.sdpSetting.award;tweeter#app.sdp.sdpSetting.common;ec#app.marketing.setCouponEdit;ec#app.marketing.multiOnePriceList;ec#app.marketing.channeledit;ec#app.marketing.channellist;foundation#app.mass.kf;foundation#app.mass.template;zhan#app.channel.manager;foundation#app.mass.sms;ec#app.marketing.setCouponList;zhan#app.dashboard;foundation#app.mass.records;ec#app.marketing.combinationlist;zhan#app.flow;ec#app.marketing.creditsAddGoodsList;foundation#app.mass.senior;ec#app.marketing.creditsGoodsList;zhan#app.flow.analytics.users;ec#app.marketing.creditsEdit;zhan#app.flow.analytics.chargeGuide;ec#app.marketing.recordList;promotion#app.recommend.activityList;promotion#app.recommend.awardMemberList;foundation#app.getCard.list;ec#app.marketing.cycleReserveList;foundation#app.care.edit;foundation#app.care.list;ec#app.marketing.cycleReserveEdit;foundation#app.getCard.edit;foundation#app.checkin.list;ec#app.marketing.combinationedit;foundation#app.checkin.rule;foundation#app.checkin.edit;foundation#app.setcoupon.list;ec#app.marketing.combinationgoodsmanage;ec#app.marketing.combinationaddgoods;foundation#app.setcoupon.edit;activity#app.box.player;activity#app.box.charts;activity#app.box.edit;activity#app.bigwheel.list;activity#app.bigwheel.prize;activity#app.bigwheel.player;activity#app.bigwheel.charts;activity#app.bigwheel.edit;ec#app.marketing.marketPromotionEdit;promotion#app.recommend.awardStrangeList;ec#app.marketing.privilegegoodsmanage;activity#app.scratch.prize;zhan#app.channel.list;foundation#app.material.tuwen;ec#app.marketing.privilegeedit;ec#app.marketing.privilegelist;ecApp#work.push#all;supplier#app.qualification.apply;foundation#app.finance;foundation#app.finance.account;foundation#app.finance.accountedit;foundation#app.finance.dealport;foundation#app.finance.refund;foundation#app.finance.withdrawport;supplier#app.qualification.application;foundation#app.baiduApp.list;foundation#app.baiduApp.version;wisdom#app.shopguide.guidemanage.guidegoalsAdd;wisdom#app.shopguide.guidemanage.performanceGoals;wisdom#app.shopguide.guidemanage.openbill;wisdom#app.shopguide.guidemanage.guideGoals;wisdom#app.shopguide.guidemanage.salesCommission;wisdom#app.shopguide.guidemanage.guidestoreAdd;wisdom#app.shopguide.guidemanage.performanceIndex;wisdom#app.shopguide.guidemanage.voucherCount;supplier#app;wisdom#app.shopguide.guidemanage.salesCommission.salesDetail;supplier#app.goods.detail;supplier#app.goods.edit;supplier#app.goods;supplier#app.goods.list;supplier#app.goods.distribution.edit;supplier#app.goods.distribution.create;supplier#app.goods.distribution;supplier#app.goods.import;supplier#app.stock;supplier#app.freight.template.edit;supplier#app.freight.template.create;supplier#app.freight.template.list;supplier#app.order.deliver;supplier#app.order.list;supplier#app.order;supplier#app.stock.list;supplier#app.qualification;supplier#app.permission.detail;supplier#app.permission;supplier#app.order.detail',
    pageElements: {
      'app-store-design-list#col-storeListFreeTable': false,
      'app-store-design-step_1#div-storeStepTitleFree': false,
      'app-wisdom-manage-store#storeType': false,
      'app.top#div-upLink': false,
      'app-financial-financialManage-weimobDetail#div-xd-tradeNo': false,
      'app-order-orderlist-deliverlist#btn-orderType': false,
      'app-dashboard#div-kindsLinksFreeTab': false,
      'app-marketing-searchSource-searchSource#div-smallShop': false,
      'app-dashboard#div-trade_analysis-xd': false,
      'app-goods-management-addGoods#div-addGoodsDesc': false,
      'app-store-design-step_2#div-storeStep2MoreBtn': false,
      'app-detailContrast#div-updateFreebtn': false,
      'app-dashboard#div-marketingFreeAct': false,
      'app-store-design-step_2#div-storeStep2FreeFootBtn': false,
    },
  },
  errmsg: '处理成功',
  errcode: '0',
});
