export default [
    {
        label:'Hello',
        path:'/button',
    },
    {
        label:'Hello',
        path:'/hello',
    },
    {
        label:'react-dnd拖拽',
        path:'/dustbin',
    },
    {
        label:"跳跳棋",
        path:"/chessboard"
    },
    {
        label:"计数器",
        path:"/counter"
    }
]